export const ISSUE_CATEGORIES: Record<string, string> = {
  "3d-printer-bed-temperature-sensor-failure": "Accessories & Aftermarket",
  "5w30-too-thin-for-sdv6": "Lubrication & Oil System",
  "8hp-gear-selector-stuck-in-park": "Transmission & Drivetrain",
  "8hp-shifter-knob-failure": "Transmission & Drivetrain",
  "a-pillar-water-leak-factory-defect": "Water Ingress",
  "ac-condenser-o-ring-mismatch": "HVAC & Climate",
  "ac-intermittent-failure": "HVAC & Climate",
  "active-anti-roll-bar-leak": "Suspension",
  "adblue-heater-fault": "Exhaust & Emissions",
  "adblue-level-low": "Exhaust & Emissions",
  "aftermarket-axle-premature-failure": "Accessories & Aftermarket",
  "aftermarket-connecting-rod-quality": "Accessories & Aftermarket",
  "aftermarket-coolant-reservoir-quality": "Accessories & Aftermarket",
  "aftermarket-propshaft-loose-differential-fit": "Transmission & Drivetrain",
  "aftermarket-propshaft-poor-fit-unbalance": "Transmission & Drivetrain",
  "aftermarket-trigger-wheel-tool-failure": "Accessories & Aftermarket",
  "aftermarket-upper-control-arm-geometry-incorrect": "Suspension",
  "air-box-not-watertight": "Water Ingress",
  "air-compressor-desiccant": "Suspension",
  "air-shock-cracking": "Suspension",
  "air-shock-replacement-needed": "Suspension",
  "air-suspension-airbag-leak": "Suspension",
  "air-suspension-complete-deflation": "Suspension",
  "air-suspension-compressor-failure": "Suspension",
  "air-suspension-compressor-filter-clogged": "Suspension",
  "air-suspension-corner-sinking": "Suspension",
  "air-suspension-drops-due-to-ecu-limp-mode": "Suspension",
  "air-suspension-drops-when-parked": "Suspension",
  "air-suspension-failure": "Suspension",
  "air-suspension-hose-damage-during-repairs": "Suspension",
  "air-suspension-leak-diagnosis-using-fuse": "Suspension",
  "air-suspension-missing-relay": "Suspension",
  "air-suspension-pressure-switch-design-flaw": "Suspension",
  "air-suspension-reservoir-solenoid-failure": "Suspension",
  "air-suspension-side-to-side-height-imbalance": "Suspension",
  "air-suspension-valve-block-o-ring-failure": "Suspension",
  "air-suspension-valve-leak-intermittent": "Suspension",
  "air-suspension-valve-pack-relocation-for-winch": "Suspension",
  "airbag-fault-b0091-door-connector": "Electrical",
  "airbox-drain-valve-failure": "Water Ingress",
  "airbox-lid-improper-seating": "Water Ingress",
  "airflow-flap-sooting": "Turbo & Intake",
  "alternator-bearing-noise": "Electrical",
  "alternator-failure": "Electrical",
  "auto-gear-linkage-bush-seized": "Transmission & Drivetrain",
  "auxiliary-battery-connector-damage": "Electrical",
  "auxiliary-battery-failure": "Electrical",
  "battery-voltage-gearbox-errors": "Electrical",
  "battery-wiring-cleanup": "Electrical",
  "body-mount-failure": "Body & Exterior",
  "boost-leak": "Turbo & Intake",
  "brake-caliper-seizure": "Brakes",
  "brake-component-crack": "Brakes",
  "brake-disc-and-pad-wear": "Brakes",
  "brake-hose-bulging": "Brakes",
  "brake-lamp-switch-contact-bounce-limp-mode": "Brakes",
  "brake-light-burnout": "Brakes",
  "brake-line-corrosion-failure": "Brakes",
  "brake-pad-wear-sensor-missing": "Brakes",
  "brake-wobble-warped-discs": "Brakes",
  "britpart-aftermarket-quality-degradation": "Accessories & Aftermarket",
  "bump-stop-installed-wrong-end": "Suspension",
  "cam-seal-leak-tdv6": "Engine Internals",
  "camshaft-seal-leak-incidental": "Engine Internals",
  "camshaft-seal-oil-leak": "Engine Internals",
  "center-armrest-handle-broken": "Interior & Controls",
  "center-bearing-failure-prop-shaft": "Transmission & Drivetrain",
  "center-console-circuit-board-failure": "Electrical",
  "central-locking-actuator-failure": "Electrical",
  "chassis-rust-cracking": "Body & Exterior",
  "chinese-diesel-heater-tank-leak": "Accessories & Aftermarket",
  "clear-coat-failure": "Body & Exterior",
  "clogged-heater-matrix": "Cooling System",
  "clogged-piston-cooling-squirters": "Engine Internals",
  "clutch-pedal-bracket-fatigue-crack": "Transmission & Drivetrain",
  "clutch-wear": "Transmission & Drivetrain",
  "cold-start-oil-drain-back": "Engine Internals",
  "components-failing-after-rebuild": "Engine Internals",
  "conrod-bearing-wear-tdv6": "Engine Internals",
  "coolant-expansion-tank-sensor-failure": "Cooling System",
  "coolant-leak-cracked-plastic-manifold": "Cooling System",
  "coolant-leak-plastic-manifold": "Cooling System",
  "coolant-leak-slow": "Cooling System",
  "coolant-level-sensor-false-warning": "Cooling System",
  "coolant-pipe-split": "Cooling System",
  "corroded-brake-lines": "Brakes",
  "corroded-ground-stud": "Electrical",
  "crankshaft-bearing-carrier-leak": "Engine Internals",
  "crankshaft-bearing-failure-lifecycle": "Engine Internals",
  "crankshaft-failure-exchange-engine": "Engine Internals",
  "crankshaft-journal-wear": "Engine Internals",
  "crankshaft-runout-rejection": "Engine Internals",
  "crankshaft-seal-install-tdv6": "Engine Internals",
  "crankshaft-trigger-wheel-failure": "Engine Internals",
  "crossover-pipe-cracking": "Cooling System",
  "cv-boot-torn": "Transmission & Drivetrain",
  "d4-a-pillar-water-leak": "Water Ingress",
  "d4-seized-tow-bar-hitch": "Body & Exterior",
  "d4-tow-bar-chassis-wear-recall": "Body & Exterior",
  "dangerous-wiring-from-workshop": "Electrical",
  "dealer-misdiagnosis-driveshaft": "Transmission & Drivetrain",
  "diesel-heater-coolant-pump-leak": "Accessories & Aftermarket",
  "diesel-heater-danger-power-loss": "Accessories & Aftermarket",
  "diesel-heater-problems": "Accessories & Aftermarket",
  "diesel-heater-trips-goal-zero-12v-fuse": "Accessories & Aftermarket",
  "differential-vent-hose-blocked": "Transmission & Drivetrain",
  "discovery-4-brake-rattle": "Brakes",
  "discovery-4-corroded-ground-points": "Electrical",
  "discovery-4-corroded-hidden-ground-cable": "Electrical",
  "discovery-4-dead-ac-system": "HVAC & Climate",
  "discovery-4-prior-amateur-work-signs": "General & Ownership",
  "discovery-4-prior-transmission-work-evidence": "Transmission & Drivetrain",
  "discovery-4-synthetic-winch-rope-needed": "Accessories & Aftermarket",
  "door-handle-emblem-fading": "Body & Exterior",
  "dpf-blocked": "Exhaust & Emissions",
  "dpf-problems": "Exhaust & Emissions",
  "drilled-brake-disc-direction": "Brakes",
  "drive-belt-contamination": "Engine Internals",
  "drive-belt-tensioner-bearing-failure": "Engine Internals",
  "drive-shaft-center-bearing-failure": "Transmission & Drivetrain",
  "driveshaft-boot-deterioration": "Transmission & Drivetrain",
  "driveshaft-center-bearing-failure": "Transmission & Drivetrain",
  "driveshaft-misdiagnosis": "Transmission & Drivetrain",
  "driveshaft-tripod-joint-play-clonking": "Transmission & Drivetrain",
  "drone-ice-buildup-engine-fault": "Electrical",
  "dsc-abs-module-failure": "Electrical",
  "dsc-fault-suspension-drop": "Suspension",
  "dual-mass-flywheel-wear": "Transmission & Drivetrain",
  "egr-valve-fomoco-oil-pump-prefix": "Exhaust & Emissions",
  "egr-valve-position-sensor-fault": "Exhaust & Emissions",
  "egr-valve-seizure": "Exhaust & Emissions",
  "electric-parking-brake-failure": "Brakes",
  "electric-parking-brake-module-degraded-grease": "Brakes",
  "electric-parking-brake-module-failure": "Brakes",
  "electronic-parking-brake-failure": "Brakes",
  "electronic-parking-brake-module-failure": "Brakes",
  "engel-fridge-inrush-current-trips-goal-zero": "Accessories & Aftermarket",
  "engine-bearing-chips-in-oil": "Engine Internals",
  "engine-bearing-failure": "Engine Internals",
  "engine-bearing-wear-glitter-inspection": "Engine Internals",
  "engine-cold-start-rattle": "Engine Internals",
  "engine-drop-in-alignment": "Engine Internals",
  "engine-ticking-warm": "Engine Internals",
  "engine-whistling-noise": "Engine Internals",
  "epb-actuator-seizure-prevention": "Brakes",
  "epb-actuator-slip-clutch-failure": "Brakes",
  "epb-cable-routing-mistake": "Brakes",
  "epb-emergency-release-cable-rubbing-driveshaft": "Brakes",
  "eu3-eu4-power-steering-line-incompatibility": "Steering",
  "exhaust-gas-temperature-sensor-failure": "Exhaust & Emissions",
  "fbh-cabin-heating-slow-without-diverter-valve": "HVAC & Climate",
  "fbh-flame-detected-fault": "HVAC & Climate",
  "fbh-premature-flame-detection": "HVAC & Climate",
  "fbh-remote-start-not-fitted": "HVAC & Climate",
  "fbh-scheduling-impracticality": "HVAC & Climate",
  "fbh-smoke-on-startup": "HVAC & Climate",
  "flywheel-timing-misalignment": "Engine Internals",
  "frame-corrosion-sdv6": "Body & Exterior",
  "freelancer-turbo-misdiagnosis": "General & Ownership",
  "fretting-rust-transmission-mating": "Transmission & Drivetrain",
  "front-bumper-mounting-points-snapping": "Body & Exterior",
  "front-differential-fluid-degradation": "Transmission & Drivetrain",
  "front-differential-leak-clogged-breather": "Transmission & Drivetrain",
  "front-differential-pinion-seal-leak": "Transmission & Drivetrain",
  "front-lower-arms-wear": "Suspension",
  "front-lower-suspension-arm-wear": "Suspension",
  "front-suspension-bushing-clonk": "Suspension",
  "front-suspension-bushing-wear": "Suspension",
  "front-wheel-bearing-premature-failure": "Wheels & Tires",
  "fuel-filter-restriction": "Fuel System",
  "fuel-gauge-sensor-failure": "Fuel System",
  "fuel-sensor-circuit-fault-cold-weather": "Fuel System",
  "gapt2d-brake-bleeding-procedure-unclear": "Brakes",
  "gates-tensioner-failure": "Engine Internals",
  "gearbox-harsh-shifting": "Transmission & Drivetrain",
  "gen-2-engine-identification": "Engine Internals",
  "glow-plug-failure": "Engine Internals",
  "ground-pin-corrosion-engine-fault": "Electrical",
  "head-gasket-grade-mismatch-with-new-pistons": "Engine Internals",
  "headlight-yellowing": "Body & Exterior",
  "heated-mirror-short-circuit": "Electrical",
  "heater-blend-door-motor": "HVAC & Climate",
  "height-sensor-calibration-after-arm-replacement": "Suspension",
  "high-pressure-fuel-pump-failure": "Fuel System",
  "hitachi-air-compressor-housing-crack": "Suspension",
  "hydraulic-sway-bar-actuator-play": "Suspension",
  "idler-pulley-bearing-quality": "Engine Internals",
  "inlet-manifold-crack": "Turbo & Intake",
  "inner-tire-wear-camber-deviation": "Wheels & Tires",
  "input-shaft-fretting-rust": "Transmission & Drivetrain",
  "insurance-difficulty": "General & Ownership",
  "intake-hose-blowoff": "Turbo & Intake",
  "intake-manifold-carbon-buildup": "Turbo & Intake",
  "intake-manifold-crack": "Turbo & Intake",
  "intake-manifold-cracking-3l-only": "Turbo & Intake",
  "intake-pipe-bolt-missing": "Turbo & Intake",
  "intake-pipe-o-ring-seal-slip": "Turbo & Intake",
  "intercooler-corrosion": "Turbo & Intake",
  "intercooler-hose-failure": "Turbo & Intake",
  "intercooler-leak": "Turbo & Intake",
  "key-replacement-cost": "General & Ownership",
  "king-bearing-incompatibility-early-tdv6": "Engine Internals",
  "licence-plate-light-failure": "Electrical",
  "loose-suspension-bolt-after-rebuild": "Suspension",
  "loose-wheel-nuts-safety": "Wheels & Tires",
  "low-oil-pressure-aftermarket-pump": "Lubrication & Oil System",
  "low-oil-pressure-tdv6": "Lubrication & Oil System",
  "low-oil-pressure-worn-pump": "Lubrication & Oil System",
  "maf-sensor-failure-restricted-performance": "Turbo & Intake",
  "maf-sensor-tube-gasket-failure": "Turbo & Intake",
  "main-bearing-condition-tdv6": "Engine Internals",
  "main-bearing-seizure-tdv6": "Engine Internals",
  "main-fuse-blown-after-rebuild": "Electrical",
  "manual-transmission-fluid-never-changed": "Transmission & Drivetrain",
  "master-brake-cylinder-failure": "Brakes",
  "mismatched-underbody-fasteners": "Body & Exterior",
  "muffler-removal-difficulty": "Exhaust & Emissions",
  "no-oil-pressure-first-start": "Lubrication & Oil System",
  "no-start-electrical": "Electrical",
  "nuisance-fault-control-module-communication-bus-off": "Electrical",
  "oil-cooler-age-failure": "Lubrication & Oil System",
  "oil-cooler-failure": "Lubrication & Oil System",
  "oil-cooler-leak-fallen-bolts": "Lubrication & Oil System",
  "oil-cooler-line-misrouted": "Lubrication & Oil System",
  "oil-filter-smaller-on-d4": "Lubrication & Oil System",
  "oil-gallery-contamination-after-line-boring": "Lubrication & Oil System",
  "oil-leak-camshaft-seal": "Lubrication & Oil System",
  "oil-leak-transmission-transfer-case": "Lubrication & Oil System",
  "oil-leaks-electrical-gremlins": "Lubrication & Oil System",
  "oil-level-reading-confusion": "Lubrication & Oil System",
  "oil-level-sensor-failure": "Lubrication & Oil System",
  "oil-level-sensor-leak": "Lubrication & Oil System",
  "oil-pressure-monitoring-upgrade": "Lubrication & Oil System",
  "oil-pressure-specs-degraded-on-sdv6": "Lubrication & Oil System",
  "oil-pressure-within-spec": "Lubrication & Oil System",
  "oil-pump-casting-failure-tdv6": "Lubrication & Oil System",
  "oil-pump-failure-tdv6": "Lubrication & Oil System",
  "oil-pump-housing-failure": "Lubrication & Oil System",
  "oil-pump-housing-failure-discovery-3": "Lubrication & Oil System",
  "oil-pump-housing-failure-pre-2009": "Lubrication & Oil System",
  "oil-pump-replacement": "Lubrication & Oil System",
  "oil-pump-seal-failure-aftermarket": "Lubrication & Oil System",
  "oil-pump-tensioner-lug-failure": "Lubrication & Oil System",
  "oil-pump-version-identification": "Lubrication & Oil System",
  "oil-pump-weak-spot-tdv6": "Lubrication & Oil System",
  "oil-pump-wear-reduced-pressure": "Lubrication & Oil System",
  "oil-sensor-connector-slide-off": "Lubrication & Oil System",
  "oil-separator-leak": "Lubrication & Oil System",
  "oil-separator-removal-difficulty": "Lubrication & Oil System",
  "oil-specification-compromise-post-rebuild": "Lubrication & Oil System",
  "oil-temperature-sensor-unplugged": "Lubrication & Oil System",
  "p2290-high-pressure-fuel-rail-low": "Fuel System",
  "paint-oxidation-clearcoat": "Body & Exterior",
  "parking-brake-bypass": "Brakes",
  "parking-brake-cable-corrosion": "Brakes",
  "parking-brake-cable-loose": "Brakes",
  "parking-brake-failure": "Brakes",
  "parking-brake-missing-fuse": "Brakes",
  "pcv-diaphragm-failure": "Lubrication & Oil System",
  "phone-not-fitted-message": "Interior & Controls",
  "pinched-wiring-harness": "Electrical",
  "piston-skirt-wear-tdv6": "Engine Internals",
  "plastic-inlet-manifold-cracking": "Turbo & Intake",
  "polyurethane-bushings-not-suitable-for-d3-d4": "Suspension",
  "power-steering-fluid-never-changed": "Steering",
  "power-steering-hose-failure": "Steering",
  "power-steering-pump-whine": "Steering",
  "power-window-central-locking-failure": "Electrical",
  "prince-charming-block-crack": "Engine Internals",
  "prolonged-cranking-bearing-damage": "Engine Internals",
  "prop-shaft-center-bearing-bounce": "Transmission & Drivetrain",
  "prop-shaft-center-bearing-failure": "Transmission & Drivetrain",
  "propshaft-center-bearing-rubber-disintegration": "Transmission & Drivetrain",
  "propshaft-center-bearing-rubber-failure": "Transmission & Drivetrain",
  "propshaft-cv-joint-failure-aftermarket": "Transmission & Drivetrain",
  "rear-anti-roll-bar-link-failure": "Suspension",
  "rear-brake-caliper-seized-guide-pins": "Brakes",
  "rear-brake-corrosion-despite-minimal-wear": "Brakes",
  "rear-brake-wear": "Brakes",
  "rear-crankshaft-seal-leak": "Engine Internals",
  "rear-diff-drain-plug-seized": "Transmission & Drivetrain",
  "rear-door-lock-failure": "Electrical",
  "rear-door-lock-intermittent": "Electrical",
  "rear-hatch-electric-lock-cable-snap": "Electrical",
  "rear-hatch-latch-false-open-warning": "Electrical",
  "rear-hatch-winch-cable-broken": "Body & Exterior",
  "rear-high-mount-stop-light-leak": "Water Ingress",
  "rear-high-pressure-diesel-pump-belt-failure": "Fuel System",
  "rear-number-plate-lamp-failure": "Electrical",
  "rear-suspension-bushing-failure": "Suspension",
  "rear-suspension-bushing-torque-at-ride-height": "Suspension",
  "rear-sway-bar-corrosion": "Suspension",
  "recurring-cv-boot-failure": "Transmission & Drivetrain",
  "reliability-expectations": "General & Ownership",
  "reversed-polarity-blown-main-fuse": "Electrical",
  "sdv6-bearing-failure-oil-starvation": "Engine Internals",
  "sdv6-center-bearing-rubber-failure": "Transmission & Drivetrain",
  "sdv6-chain-guide-disintegration": "Engine Internals",
  "sdv6-egr-gasket-unobtainium": "Exhaust & Emissions",
  "sdv6-engine-failure-original-engine-confirmed": "Engine Internals",
  "sdv6-gen2-oil-dilution": "Lubrication & Oil System",
  "sdv6-head-gasket-leak": "Engine Internals",
  "sdv6-intake-oil-contamination": "Lubrication & Oil System",
  "sdv6-oil-dilution": "Lubrication & Oil System",
  "sdv6-oil-starvation-piston-melt": "Engine Internals",
  "sdv6-rear-crankshaft-seal-leak": "Engine Internals",
  "sdv6-snapped-crankshaft": "Engine Internals",
  "seized-brake-caliper-guide-pin": "Brakes",
  "serpentine-belt-misrouting": "Engine Internals",
  "serpentine-belt-tensioner-bounce": "Engine Internals",
  "serpentine-belt-tensioner-broken": "Engine Internals",
  "snorkel-diaphragm-broken": "Accessories & Aftermarket",
  "snorkel-increased-fuel-consumption": "Accessories & Aftermarket",
  "snorkel-ram-air-fuel-consumption-increase": "Accessories & Aftermarket",
  "spare-wheel-carrier-wrong-installation": "Body & Exterior",
  "spontaneous-crankshaft-cracking": "Engine Internals",
  "spun-main-bearings": "Engine Internals",
  "start-stop-anxiety": "General & Ownership",
  "start-stop-button-lettering-worn": "Interior & Controls",
  "steering-knuckle-play": "Steering",
  "steering-rack-condition": "Steering",
  "steering-wheel-controls-worn": "Interior & Controls",
  "sticky-buttons-soft-touch-coating": "Interior & Controls",
  "sump-inspection-metallic-chips": "Engine Internals",
  "sunroof-drain-blocked-by-foam": "Water Ingress",
  "sunroof-seal-water-ingress": "Water Ingress",
  "suspension-control-arm-wear": "Suspension",
  "suspension-height-calibration-aftermarket-arms": "Suspension",
  "tdv6-bearing-failure-design-compromise": "Engine Internals",
  "tdv6-spun-main-bearings": "Engine Internals",
  "throttle-body-crack": "Turbo & Intake",
  "throttle-body-emissions-only": "Turbo & Intake",
  "timing-belt-failure": "Engine Internals",
  "timing-belt-replacement-critical": "Engine Internals",
  "timing-belt-wear": "Engine Internals",
  "timing-chain-failure-5l-v8": "Engine Internals",
  "tire-flat-spots": "Wheels & Tires",
  "tire-pressure-control-module-failure": "Wheels & Tires",
  "transfer-case-breather-tube-leak": "Transmission & Drivetrain",
  "transfer-case-fluid-water-contamination": "Transmission & Drivetrain",
  "transfer-case-input-seal-leak": "Transmission & Drivetrain",
  "transmission-oil-leak": "Transmission & Drivetrain",
  "transmission-oil-pan-seal-incorrectly-installed": "Transmission & Drivetrain",
  "trigger-wheel-installation-error": "Engine Internals",
  "turbo-actuator-sticking": "Turbo & Intake",
  "turbo-boost-hose-blown-off": "Turbo & Intake",
  "turbo-hose-clamp-snapped": "Turbo & Intake",
  "turbo-soot-clogging": "Turbo & Intake",
  "turbocharger-bypass-valve-connector": "Turbo & Intake",
  "turbocharger-hose-deterioration": "Turbo & Intake",
  "turbocharger-linkage-seizure": "Turbo & Intake",
  "turbocharger-seizure-oil-contamination": "Turbo & Intake",
  "tuv-failure-killing-vehicles": "General & Ownership",
  "twin-turbo-replacement": "Turbo & Intake",
  "underbody-chassis-rust": "Body & Exterior",
  "underbody-corrosion-structural": "Body & Exterior",
  "underbody-rust": "Body & Exterior",
  "upper-control-arm-bushing-wear": "Suspension",
  "upper-tailgate-actuator-failure": "Body & Exterior",
  "vacuum-pump-leak": "Engine Internals",
  "valve-stem-seal-failure": "Engine Internals",
  "viscous-fan-clutch-cold-start-noise": "Cooling System",
  "water-connection-housing-crack": "Cooling System",
  "water-connection-housing-leak": "Cooling System",
  "water-in-diesel-filter": "Fuel System",
  "water-pump-bearing-wear": "Cooling System",
  "water-pump-failure": "Cooling System",
  "wheel-bearing-failure": "Wheels & Tires",
  "wheel-lug-nut-swelling": "Wheels & Tires",
  "windscreen-chip-tuv-failure": "General & Ownership",
  "windscreen-cowl-water-ingress": "Water Ingress",
  "windshield-misting-sensor-failure": "Electrical",
  "windshield-sensor-missing": "Electrical",
  "worn-halfshaft-cv-joints": "Transmission & Drivetrain",
  "worn-steering-knuckle-ball-joint": "Steering",
  "wrong-oil-specification-tdv6": "Lubrication & Oil System",
  "xenon-headlight-dipped-beam-cutout": "Electrical",
  "zf-6hp-mechatronic-seal-failure": "Transmission & Drivetrain",
  "zf-8hp-transmission-shudder": "Transmission & Drivetrain",
  "zf-8hp70-casting-defect-oil-leak": "Transmission & Drivetrain",
  "zf-transmission-fluid-overdue": "Transmission & Drivetrain",
};

export function categorizeIssue(slug: string): string {
  return ISSUE_CATEGORIES[slug] ?? "Other";
}
